rplidar_node:
  ros__parameters:
    channel_type: serial
    serial_port: /dev/lidar_usb
    serial_baudrate: 1000000
    frame_id: laser_frame
    inverted: false
    angle_compensate: true
    scan_mode: DenseBoost
